[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ychackathon"
version = "0.1.0"
description = "A project for text classification using Huggingface/Transformers"
dependencies = [
    "transformers>=4.9.2",
    "datasets>=1.11.0"
]
