[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ychackathon"
version = "0.1.0"
dependencies = [
    "anthropic",
    "scikit-learn",
    "numpy",
    "transformers",
    "datasets",
    "pandas"
]
