[project]
name = "ychackathon"
version = "0.1.0"
description = "A project for text classification using Huggingface/Transformers"

[dependencies]
python = ">=3.8"
transformers = ">=4.9.2"
datasets = ">=1.11.0"

[build-system]
requires = ["uv"]
build-backend = "uv.build"
